# This is a basic workflow that is manually triggered

name: GraphQL test CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew test allureReport
        continue-on-error: true
      - name: Save Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./build/reports/allure-report/